FROM golang:1.24 as builder

WORKDIR /app
ENV GO111MODULE=on

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN apk add --no-cache findutils && \
    find . -maxdepth=2 | sort

RUN CGO_ENABLED=0 go build -o generate ./cmd/generate