FROM golang:1.25 as builder

WORKDIR /app
ENV GO111MODULE=on

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go tool templ generate

RUN CGO_ENABLED=0 go build -o generate ./cmd/generate

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/generate ./

CMD ["./generate"]
