FROM golang:1.24 as builder

WORKDIR /app
ENV GO111MODULE=on

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN apt-get update && apt-get install -y findutils && \
    find . -maxdepth 4 | sort

RUN CGO_ENABLED=0 go build -o generate ./cmd/generate