service: angular-serverless-app

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-api-compression
  - serverless-associate-waf

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  timeout: 10
  region: us-east-1
  deploymentBucket:

package:
  excludeDevDependencies: true
  patterns:
    - '!src/**'
    - 'src/assets/**'
    - '!node_modules/**'
    - '!firebug-lite/**'
    - '!e2e/**'
    - '!coverage/**'
    - '!.angular/**'
    - '!.vscode/**'
    - node_modules/@vendia/**
    - node_modules/aws-serverless-express/**
    - node_modules/binary-case/**
    - node_modules/type-is/**
    - node_modules/media-typer/**
    - node_modules/mime-types/**
    - node_modules/mime-db/**
    - node_modules/@codegenie/serverless-express/**

custom:
  serverless-offline:
    noPrependStageInUrl: true
  contentCompression: 1024
  apigwBinary:
    types:
      - 'image/jpeg'
      - 'image/png'
      - 'image/gif'
      - 'application/font-woff'
      - 'application/font-woff2'
      - 'application/vnd.ms-fontobject'
      - 'application/x-font-ttf'
      - 'font/opentype'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY /{proxy+}
      - http: ANY /
