name: Deploy Release

permissions:
  contents: read
  id-token: write

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository at tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::812100404712:role/role-lofi-code-githubci
          aws-region: us-east-1

      - name: Deploy application
        run: make deploy
