name: Deploy Release

permissions:
  contents: read
  id-token: write

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository at tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::812100404712:role/role-lofi-code-githubci
          aws-region: us-east-1

      - name: Decode and write environment.prod.ts
        run: |
          echo "${{ secrets.ENV_PROD_TS }}" | base64 --decode > src/environments/environment.prod.ts

      - name: Deploy to AWS S3
        run: npm run deploy